// Generated by CoffeeScript 2.5.1
(function() {
  var bufferToBigInt, bufferToHexBrowser, bufferToHexNode, bufferToUtf8, byteToHex, hexToBufferBrowser, hexToBufferNode, utf8ToBufferBrowser, utf8ToBufferNode;

  Object.defineProperty(exports, "__esModule", {
    value: true
  });

  //###########################################################
  byteToHex = function(byte) {
    byte = byte & 0xFF;
    return byte.toString(16).padStart(2, '0');
  };

  //###########################################################
  bufferToBigInt = function(byteBuffer) {
    var byte, i, j, len, value;
    byteBuffer = new Uint8Array(byteBuffer);
    value = 0n;
    for (i = j = 0, len = byteBuffer.length; j < len; i = ++j) {
      byte = byteBuffer[i];
      value += BigInt(byte) << (8n * BigInt(i));
    }
    return value;
  };

  //###########################################################
  bufferToUtf8 = function(byteBuffer) {
    var byteArray;
    byteArray = new Uint8Array(byteBuffer);
    return String.fromCharCode.apply(null, byteArray);
  };

  //###########################################################
  bufferToHexBrowser = function(byteBuffer) {
    var byteArray;
    byteArray = new Uint8Array(byteBuffer);
    return Array.prototype.map.call(byteArray, byteToHex).join("");
  };

  bufferToHexNode = function(byteBuffer) {
    return Buffer.from(byteBuffer).toString("hex");
  };

  //###########################################################
  hexToBufferBrowser = function(hex) {
    var i, j, ref, result;
    result = new Uint8Array(hex.length / 2);
    for (i = j = 0, ref = hex.length; j < ref; i = j += 2) {
      result[i / 2] = parseInt(hex.substr(i, 2), 16);
    }
    return result.buffer;
  };

  hexToBufferNode = function(hex) {
    return Buffer.from(hex, 'hex');
  };

  
  //###########################################################
  utf8ToBufferNode = function(utf8) {
    return Buffer.from(utf8, "utf8");
  };

  utf8ToBufferBrowser = function(utf8) {
    var bytes;
    bytes = (new TextEncoder()).encode(utf8);
    return bytes.buffer;
  };

  //###########################################################
  if (typeof window === "object") {
    exports.bufferToBigInt = bufferToBigInt;
    exports.bytesToBigInt = bufferToBigInt;
    exports.bufferToUtf8 = bufferToUtf8;
    exports.bytesToUtf8 = bufferToUtf8;
    exports.utf8ToBuffer = utf8ToBufferBrowser;
    exports.utf8ToBytes = utf8ToBufferBrowser;
    exports.bufferToHex = bufferToHexBrowser;
    exports.bytesToHex = bufferToHexBrowser;
    exports.hexToBuffer = hexToBufferBrowser;
    exports.hexToBytes = hexToBufferBrowser;
  } else {
    exports.bufferToBigInt = bufferToBigInt;
    exports.bytesToBigInt = bufferToBigInt;
    exports.bufferToUtf8 = bufferToUtf8;
    exports.bytesToUtf8 = bufferToUtf8;
    exports.utf8ToBuffer = utf8ToBufferNode;
    exports.utf8ToBytes = utf8ToBufferNode;
    exports.bufferToHex = bufferToHexNode;
    exports.bytesToHex = bufferToHexNode;
    exports.hexToBuffer = hexToBufferNode;
    exports.hexToBytes = hexToBufferNode;
  }

}).call(this);
